### ISSUE TITLE
Adjust to the updates of RFC9175

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#273]
Should have really happened while that was still a draft...

Relevant items:
* [ ] Client-side automatic Echo answering
* [ ] Server side amplification mitigation
* [ ] Sequential token values for DTLS
* Request-Tag for
  * [ ] simultaneous requests
  * [ ] inner-blockwise assembly (with the stricter rules on concluded operations)
